spring:
    datasource:
#    连接池:据说最好的-阿里的
        type: com.alibaba.druid.pool.DruidDataSource
#        驱动  mysql
        driverClassName: com.mysql.jdbc.Driver
        druid:
            default:  #默认数据源
#              url: jdbc:mysql://59.110.240.154:3306/boot_base?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
              url: jdbc:mysql://localhost:3306/boot_base_all?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
#              账户
              username: root
#              密码
              password: root1234
            second:  #第二个数据源
                #              url: jdbc:mysql://59.110.240.154:3306/boot_base?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                url: jdbc:mysql://localhost:3306/boot_base_all?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                #              账户
                username: root
                #              密码
                password: root1234
#              连接池启动时的初始值.
            initial-size: 10
#            连接池的最大值
            max-active: 1000
#            最大空闲值.当经过一个高峰时间后，连接池可以慢慢将已经用不到的连接慢慢释放一部分，一直减少到maxIdle为止
#            max-idle: 10
#            最小空闲值.当空闲的连接数少于阀值时，连接池就会预申请去一些连接，以免洪峰来时来不及申请。
            min-idle: 10
#            最大等待值
            max-wait: 60000
#             打开PSCache，并且指定每个连接上PSCache的大小
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: 123456
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

